### ISSUE TITLE
Undefined variable: boletos

### ISSUE THREAD

**Issue by ghost** [matheushack/itauboleto#5]
Severity: Notice
Message: Undefined variable: boletos
Filename: controllers/Boletos.php
Line Number: 122
 $boletosRegistrados = $itau->registrar($boletos, $dadosComplementares);

essa linha a variavel $boletos precisa ser alterada para $boleto.

**Comment by matheushack** [comment]
Esse arquivo não faz parte do meu projeto e sim do projeto que está implementando o ItauBoleto
